### ISSUE TITLE
This project uses Tensorflow 1.x

### ISSUE THREAD

**Issue by abhi-kolluri** [anikethjr/NER_Telugu#2]
currently all the consoles have upgraded to tensorflow 2.x no console such as jupyter notebook or coolabs supports its exexcution
eitther change the whole code to support tensorflow to 2.x

**Comment by anikethjr** [comment]
Sorry for the delayed response. I am currently not working on this repo actively, so I'll be unable to update the code. You can run the code using Tensorflow 1.x if you install the older version or create a Conda environment with it.

Best,
Aniketh
